"""Splits the live vector logo (public/brand/logo-source.svg, from botanicoir.com's theme) into named parts for
components/Logo.tsx and the preloader, and writes lib/logo.ts.

The source draws, in a 542.73 x 191.32 box:
  0      the leaf (gradient #99ca3c to #218c44)
  1      the leaf's veins, a single polygon (white)
  2-11   "Botanicoir": B, o, t, a, n+i stem, i dot, c, o, i dot, r+i stem
  12-37  "Producers of Quality Cocopeat"
  38-39  the registered mark
Every path except the veins carries transform="translate(-180.35 -320.28)"; it is applied here as a group offset so
the numbers stay exactly as published."""
import re, json, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
svg = (root / "public/brand/logo-source.svg").read_text()
els = re.findall(r'<(path|polygon)([^>]*)/?>', svg)
attr = lambda a, k: re.search(k + r'="([^"]+)"', a).group(1)
shapes = [attr(a, "d") if t == "path" else attr(a, "points") for t, a in els]

# x of each glyph's first point (after the offset) orders the letters left to right for the stagger.
def x0(d): return float(re.findall(r'-?\d+\.?\d*', d)[0]) - 180.35
letters = sorted(shapes[2:12], key=x0)
out = {
    "viewBox": "0 0 542.73 191.32",
    "offset": [-180.35, -320.28],
    "leaf": shapes[0],
    "veins": shapes[1],
    "letters": letters,
    "tagline": shapes[12:38],
    "registered": shapes[38:40],
    "gradient": {"x1": 397.88, "y1": 388.92, "x2": 440.28, "y2": 330.57, "from": "#99ca3c", "to": "#218c44", "at": 0.37},
}
ts = "// Generated by scripts/logo.py from the live botanicoir.com logo. Do not edit by hand.\n"
for k, v in out.items():
    ts += f"export const {k.upper() if k != 'viewBox' else 'VIEWBOX'} = {json.dumps(v)}{' as const' if isinstance(v, list) and k == 'offset' else ''};\n"
(root / "lib").mkdir(exist_ok=True)
(root / "lib/logo.ts").write_text(ts)
print("letters", len(letters), "tagline", len(out["tagline"]))
